import {
    LayoutDashboard,
    Box,
    Layers,
    Package,
    Users,
    TrendingUp,
    Sparkles,
    Settings,
    Database,
    Building2,
    Briefcase,
    Clock,
    FileText,
    CalendarDays,
    DollarSign,
    BarChart3,
    ClipboardList,
    MapPin,
    Truck,
    ShoppingCart,
    ArrowRightLeft,
    ClipboardCheck,
    Store,
    Banknote,
    Shield,
    LucideIcon,
} from "lucide-react"

export interface SubNavItem {
    href: string
    label: string
    icon: LucideIcon
}

export interface NavItem {
    href: string
    label: string
    icon: LucideIcon
    iconBg: string
    iconColor: string
    activeIconBg: string
    activeBg: string
    activeBorder: string
    activeText: string
    badge: string | null
    requiredRole?: string
    requiredPermission?: string
    requiredModule?: string
    subItems?: SubNavItem[]
}

export const adminNavItems: NavItem[] = [
    {
        href: "/admin",
        label: "Dashboard",
        icon: LayoutDashboard,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
    },
    {
        href: "/admin/sales",
        label: "Sales",
        icon: TrendingUp,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredModule: "SALES",
        subItems: [
            {
                href: "/admin/sales/pos",
                label: "POS",
                icon: Store,
            },
            {
                href: "/admin/sales/sales-orders",
                label: "Sales Order",
                icon: ShoppingCart,
            },
            {
                href: "/admin/sales/price-list",
                label: "Price List",
                icon: FileText,
            },
            {
                href: "/admin/sales/sales-returns",
                label: "Sales Return",
                icon: ArrowRightLeft,
            },
        ],
    },
    {
        href: "/admin/purchase",
        label: "Purchase",
        icon: ShoppingCart,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredModule: "PURCHASE",
        subItems: [
            {
                href: "/admin/purchase/suppliers",
                label: "Suppliers",
                icon: Truck,
            },
            {
                href: "/admin/purchase/purchase-requests",
                label: "Purchase Request",
                icon: ClipboardList,
            },
            {
                href: "/admin/purchase/purchase-orders",
                label: "Purchase Order",
                icon: ShoppingCart,
            },
            {
                href: "/admin/purchase/goods-receipts",
                label: "Penerimaan Barang",
                icon: Package,
            },
            {
                href: "/admin/purchase/purchase-returns",
                label: "Purchase Return",
                icon: ArrowRightLeft,
            },
        ],
    },
    {
        href: "/admin/inventory",
        label: "Inventory",
        icon: Package,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredModule: "INVENTORY",
        subItems: [
            {
                href: "/admin/inventory/items",
                label: "Items",
                icon: Box,
            },
            {
                href: "/admin/inventory/categories",
                label: "Categories",
                icon: Layers,
            },
            {
                href: "/admin/inventory/warehouses",
                label: "Warehouses",
                icon: MapPin,
            },
            {
                href: "/admin/inventory/stock-movements",
                label: "Stock Movement",
                icon: TrendingUp,
            },
            {
                href: "/admin/inventory/stock-transfers",
                label: "Stock Transfer",
                icon: ArrowRightLeft,
            },
            {
                href: "/admin/inventory/stock-adjustments",
                label: "Stock Adjustment",
                icon: Settings,
            },
            {
                href: "/admin/inventory/stock-opnames",
                label: "Stock Opname",
                icon: ClipboardCheck,
            },
        ],
    },
    {
        href: "/admin/production",
        label: "Production",
        icon: Building2,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredModule: "PRODUCTION",
        subItems: [
            {
                href: "/admin/production/bill-of-materials",
                label: "Bill of Materials",
                icon: Layers,
            },
            {
                href: "/admin/production/production-orders",
                label: "Production Order",
                icon: ClipboardList,
            },
            {
                href: "/admin/production/work-orders",
                label: "Work Orders",
                icon: Briefcase,
            },
            {
                href: "/admin/production/production-reports",
                label: "Production Report",
                icon: BarChart3,
            },
        ],
    },
    {
        href: "/admin/finance",
        label: "Finance",
        icon: Banknote,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredModule: "FINANCE",
        subItems: [
            {
                href: "/admin/finance/invoices",
                label: "Invoices",
                icon: FileText,
            },
            {
                href: "/admin/finance/payments",
                label: "Payments",
                icon: DollarSign,
            },
            {
                href: "/admin/finance/expenses",
                label: "Expenses",
                icon: ShoppingCart,
            },
            {
                href: "/admin/finance/accounts",
                label: "Accounts",
                icon: Database,
            },
            {
                href: "/admin/finance/journal-entries",
                label: "Journal Entries",
                icon: ClipboardList,
            },
        ],
    },
    {
        href: "/admin/assets",
        label: "Assets",
        icon: Database,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredModule: "ASSETS",
        subItems: [
            {
                href: "/admin/assets/asset-register",
                label: "Asset Register",
                icon: Database,
            },
            {
                href: "/admin/assets/asset-assignments",
                label: "Asset Assignment",
                icon: Users,
            },
            {
                href: "/admin/assets/maintenance",
                label: "Maintenance",
                icon: Settings,
            },
            {
                href: "/admin/assets/depreciation",
                label: "Depreciation",
                icon: TrendingUp,
            },
        ],
    },
    {
        href: "/admin/modules",
        label: "Pengaturan Modul",
        icon: Sparkles,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredRole: "OWNER",
        requiredPermission: "modules:edit",
    },
    {
        href: "/admin/users",
        label: "Pengguna",
        icon: Users,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredPermission: "users:view",
    },
    {
        href: "/admin/roles",
        label: "Role & Akses",
        icon: Shield,
        iconBg: "bg-zinc-50",
        iconColor: "text-zinc-500",
        activeIconBg: "bg-zinc-900",
        activeBg: "bg-zinc-100/50",
        activeBorder: "bg-zinc-900",
        activeText: "text-zinc-900 font-semibold",
        badge: null,
        requiredPermission: "roles:view",
    },
]

export const getHrisNavItems = (role: string | undefined): NavItem[] => {
    const baseItems: NavItem[] = [
        {
            href: "/hris",
            label: "Dashboard",
            icon: LayoutDashboard,
            iconBg: "bg-blue-50",
            iconColor: "text-blue-500",
            activeIconBg: "bg-blue-500",
            activeBg: "bg-blue-50",
            activeBorder: "bg-blue-500",
            activeText: "text-blue-700",
            badge: null,
        },
    ]

    // OWNER - Full access to all features
    if (role === "OWNER") {
        return [
            ...baseItems,
            {
                href: "/hris/masterdata",
                label: "Master Data",
                icon: Database,
                iconBg: "bg-orange-50",
                iconColor: "text-orange-500",
                activeIconBg: "bg-orange-500",
                activeBg: "bg-orange-50",
                activeBorder: "bg-orange-500",
                activeText: "text-orange-700",
                badge: null,
                subItems: [
                    {
                        href: "/hris/masterdata/departments",
                        label: "Departemen",
                        icon: Building2,
                    },
                    {
                        href: "/hris/masterdata/positions",
                        label: "Posisi",
                        icon: Briefcase,
                    },
                ],
            },
            {
                href: "/hris/employees",
                label: "Data Pegawai",
                icon: Users,
                iconBg: "bg-violet-50",
                iconColor: "text-violet-500",
                activeIconBg: "bg-violet-500",
                activeBg: "bg-violet-50",
                activeBorder: "bg-violet-500",
                activeText: "text-violet-700",
                badge: null,
            },
            {
                href: "/hris/attendance",
                label: "Absensi",
                icon: Clock,
                iconBg: "bg-emerald-50",
                iconColor: "text-emerald-500",
                activeIconBg: "bg-emerald-500",
                activeBg: "bg-emerald-50",
                activeBorder: "bg-emerald-500",
                activeText: "text-emerald-700",
                badge: null,
            },
            {
                href: "/hris/daily-report",
                label: "Laporan Kerja",
                icon: FileText,
                iconBg: "bg-amber-50",
                iconColor: "text-amber-500",
                activeIconBg: "bg-amber-500",
                activeBg: "bg-amber-50",
                activeBorder: "bg-amber-500",
                activeText: "text-amber-700",
                badge: null,
            },
            {
                href: "/hris/leave",
                label: "Cuti & Izin",
                icon: CalendarDays,
                iconBg: "bg-rose-50",
                iconColor: "text-rose-500",
                activeIconBg: "bg-rose-500",
                activeBg: "bg-rose-50",
                activeBorder: "bg-rose-500",
                activeText: "text-rose-700",
                badge: null,
            },
            {
                href: "/hris/payroll",
                label: "Payroll",
                icon: DollarSign,
                iconBg: "bg-cyan-50",
                iconColor: "text-cyan-500",
                activeIconBg: "bg-cyan-500",
                activeBg: "bg-cyan-50",
                activeBorder: "bg-cyan-500",
                activeText: "text-cyan-700",
                badge: null,
            },
            {
                href: "/hris/reports",
                label: "Report",
                icon: BarChart3,
                iconBg: "bg-indigo-50",
                iconColor: "text-indigo-500",
                activeIconBg: "bg-indigo-500",
                activeBg: "bg-indigo-50",
                activeBorder: "bg-indigo-500",
                activeText: "text-indigo-700",
                badge: null,
                subItems: [
                    {
                        href: "/hris/reports/attendance",
                        label: "Absensi",
                        icon: ClipboardList,
                    },
                ],
            },
        ]
    }

    // HR Admin - Full access
    if (role === "HR_ADMIN") {
        return [
            ...baseItems,
            {
                href: "/hris/masterdata",
                label: "Master Data",
                icon: Database,
                iconBg: "bg-orange-50",
                iconColor: "text-orange-500",
                activeIconBg: "bg-orange-500",
                activeBg: "bg-orange-50",
                activeBorder: "bg-orange-500",
                activeText: "text-orange-700",
                badge: null,
                subItems: [
                    {
                        href: "/hris/masterdata/departments",
                        label: "Departemen",
                        icon: Building2,
                    },
                    {
                        href: "/hris/masterdata/positions",
                        label: "Posisi",
                        icon: Briefcase,
                    },
                ],
            },
            {
                href: "/hris/employees",
                label: "Data Pegawai",
                icon: Users,
                iconBg: "bg-violet-50",
                iconColor: "text-violet-500",
                activeIconBg: "bg-violet-500",
                activeBg: "bg-violet-50",
                activeBorder: "bg-violet-500",
                activeText: "text-violet-700",
                badge: null,
            },
            {
                href: "/hris/attendance",
                label: "Absensi",
                icon: Clock,
                iconBg: "bg-emerald-50",
                iconColor: "text-emerald-500",
                activeIconBg: "bg-emerald-500",
                activeBg: "bg-emerald-50",
                activeBorder: "bg-emerald-500",
                activeText: "text-emerald-700",
                badge: null,
            },
            {
                href: "/hris/daily-report",
                label: "Laporan Kerja",
                icon: FileText,
                iconBg: "bg-amber-50",
                iconColor: "text-amber-500",
                activeIconBg: "bg-amber-500",
                activeBg: "bg-amber-50",
                activeBorder: "bg-amber-500",
                activeText: "text-amber-700",
                badge: null,
            },
            {
                href: "/hris/leave",
                label: "Cuti & Izin",
                icon: CalendarDays,
                iconBg: "bg-rose-50",
                iconColor: "text-rose-500",
                activeIconBg: "bg-rose-500",
                activeBg: "bg-rose-50",
                activeBorder: "bg-rose-500",
                activeText: "text-rose-700",
                badge: "3",
            },
            {
                href: "/hris/payroll",
                label: "Payroll",
                icon: DollarSign,
                iconBg: "bg-cyan-50",
                iconColor: "text-cyan-500",
                activeIconBg: "bg-cyan-500",
                activeBg: "bg-cyan-50",
                activeBorder: "bg-cyan-500",
                activeText: "text-cyan-700",
                badge: null,
            },
            {
                href: "/hris/reports",
                label: "Report",
                icon: BarChart3,
                iconBg: "bg-indigo-50",
                iconColor: "text-indigo-500",
                activeIconBg: "bg-indigo-500",
                activeBg: "bg-indigo-50",
                activeBorder: "bg-indigo-500",
                activeText: "text-indigo-700",
                badge: null,
                subItems: [
                    {
                        href: "/hris/reports/attendance",
                        label: "Absensi",
                        icon: ClipboardList,
                    },
                ],
            },
        ]
    }

    // Manager - Team oversight + personal access
    if (role === "MANAGER") {
        return [
            ...baseItems,
            {
                href: "/hris/attendance",
                label: "Absensi",
                icon: Clock,
                iconBg: "bg-emerald-50",
                iconColor: "text-emerald-500",
                activeIconBg: "bg-emerald-500",
                activeBg: "bg-emerald-50",
                activeBorder: "bg-emerald-500",
                activeText: "text-emerald-700",
                badge: null,
            },
            {
                href: "/hris/daily-report",
                label: "Laporan Kerja",
                icon: FileText,
                iconBg: "bg-amber-50",
                iconColor: "text-amber-500",
                activeIconBg: "bg-amber-500",
                activeBg: "bg-amber-50",
                activeBorder: "bg-amber-500",
                activeText: "text-amber-700",
                badge: null,
            },
            {
                href: "/hris/leave",
                label: "Cuti & Izin",
                icon: CalendarDays,
                iconBg: "bg-rose-50",
                iconColor: "text-rose-500",
                activeIconBg: "bg-rose-500",
                activeBg: "bg-rose-50",
                activeBorder: "bg-rose-500",
                activeText: "text-rose-700",
                badge: "3",
            },
            {
                href: "/hris/reports",
                label: "Report",
                icon: BarChart3,
                iconBg: "bg-indigo-50",
                iconColor: "text-indigo-500",
                activeIconBg: "bg-indigo-500",
                activeBg: "bg-indigo-50",
                activeBorder: "bg-indigo-500",
                activeText: "text-indigo-700",
                badge: null,
                subItems: [
                    {
                        href: "/hris/reports/attendance",
                        label: "Absensi",
                        icon: ClipboardList,
                    },
                ],
            },
        ]
    }

    // Team Leader - Team oversight for their team + personal access
    if (role === "TEAM_LEADER") {
        return [
            ...baseItems,
            {
                href: "/hris/attendance",
                label: "Absensi",
                icon: Clock,
                iconBg: "bg-emerald-50",
                iconColor: "text-emerald-500",
                activeIconBg: "bg-emerald-500",
                activeBg: "bg-emerald-50",
                activeBorder: "bg-emerald-500",
                activeText: "text-emerald-700",
                badge: null,
            },
            {
                href: "/hris/daily-report",
                label: "Laporan Kerja",
                icon: FileText,
                iconBg: "bg-amber-50",
                iconColor: "text-amber-500",
                activeIconBg: "bg-amber-500",
                activeBg: "bg-amber-50",
                activeBorder: "bg-amber-500",
                activeText: "text-amber-700",
                badge: null,
            },
            {
                href: "/hris/leave",
                label: "Cuti & Izin",
                icon: CalendarDays,
                iconBg: "bg-rose-50",
                iconColor: "text-rose-500",
                activeIconBg: "bg-rose-500",
                activeBg: "bg-rose-50",
                activeBorder: "bg-rose-500",
                activeText: "text-rose-700",
                badge: null,
            },
            {
                href: "/hris/reports",
                label: "Report",
                icon: BarChart3,
                iconBg: "bg-indigo-50",
                iconColor: "text-indigo-500",
                activeIconBg: "bg-indigo-500",
                activeBg: "bg-indigo-50",
                activeBorder: "bg-indigo-500",
                activeText: "text-indigo-700",
                badge: null,
                subItems: [
                    {
                        href: "/hris/reports/attendance",
                        label: "Absensi",
                        icon: ClipboardList,
                    },
                ],
            },
        ]
    }

    // Employee, Staff - Personal access
    return [
        ...baseItems,
        {
            href: "/hris/attendance",
            label: "Absensi",
            icon: Clock,
            iconBg: "bg-emerald-50",
            iconColor: "text-emerald-500",
            activeIconBg: "bg-emerald-500",
            activeBg: "bg-emerald-50",
            activeBorder: "bg-emerald-500",
            activeText: "text-emerald-700",
            badge: null,
        },
        {
            href: "/hris/daily-report",
            label: "Laporan Kerja",
            icon: FileText,
            iconBg: "bg-amber-50",
            iconColor: "text-amber-500",
            activeIconBg: "bg-amber-500",
            activeBg: "bg-amber-50",
            activeBorder: "bg-amber-500",
            activeText: "text-amber-700",
            badge: null,
        },
        {
            href: "/hris/leave",
            label: "Cuti & Izin",
            icon: CalendarDays,
            iconBg: "bg-rose-50",
            iconColor: "text-rose-500",
            activeIconBg: "bg-rose-500",
            activeBg: "bg-rose-50",
            activeBorder: "bg-rose-500",
            activeText: "text-rose-700",
            badge: null,
        },
        {
            href: "/hris/payroll",
            label: "Slip Gaji",
            icon: DollarSign,
            iconBg: "bg-cyan-50",
            iconColor: "text-cyan-500",
            activeIconBg: "bg-cyan-500",
            activeBg: "bg-cyan-50",
            activeBorder: "bg-cyan-500",
            activeText: "text-cyan-700",
            badge: null,
        },
    ]
}
