name: XRP CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi script deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEYS }}
          port: ${{ secrets.VPS_SSH_PORT }}

          script: |
            # 1. Set PATH secara manual tanpa memanggil perintah 'go' di dalamnya
            export PATH=$PATH:/usr/local/go/bin:$(echo $HOME/go/bin)

            cd /www/wwwroot/xrp.gdv.my.id/ekserpi
            git pull origin main

            # --- DEPLOY BACKEND (GOLANG) ---
            cd backend
            /usr/local/go/bin/go build -o main . && pm2 restart xrp-api || echo "Backend build failed!"

            # --- DEPLOY FRONTEND (NEXT.JS) ---
            cd ..

            # npm install pakai npm ci, lebih cepat sesuai package-lock.json
            npm ci
            npm run build && pm2 restart xrp-app || echo "Frontend build failed!"
